export const siteConfig = {
  name: "Portal ENAMED",
  url: "https://provaenamed.com.br",
  description:
    "Portal de referência sobre o Exame Nacional de Avaliação da Formação Médica (ENAMED). Conteúdo factual, citável e atualizado para estudantes, médicos, IES e pesquisadores.",
  locale: "pt-BR",
};

export const sitemapRoutes: { path: string; changeFrequency: "daily" | "weekly" | "monthly" | "yearly"; priority: number }[] = [
  { path: "/", changeFrequency: "weekly", priority: 1.0 },
  { path: "/enamed", changeFrequency: "monthly", priority: 0.9 },
  { path: "/enamed/historia", changeFrequency: "yearly", priority: 0.7 },
  { path: "/enamed/elegibilidade", changeFrequency: "monthly", priority: 0.8 },
  { path: "/enamed/objetivos", changeFrequency: "monthly", priority: 0.7 },
  { path: "/enamed/diferencas", changeFrequency: "monthly", priority: 0.7 },
  { path: "/enamed/cronograma-aplicacao", changeFrequency: "monthly", priority: 0.8 },
  { path: "/prova-enamed", changeFrequency: "monthly", priority: 0.9 },
  { path: "/prova-enamed/teoria-resposta-item", changeFrequency: "yearly", priority: 0.8 },
  { path: "/prova-enamed/metodo-angoff", changeFrequency: "yearly", priority: 0.7 },
  { path: "/prova-enamed/numero-de-questoes", changeFrequency: "monthly", priority: 0.8 },
  { path: "/prova-enamed/tempo-de-prova", changeFrequency: "monthly", priority: 0.7 },
  { path: "/prova-enamed/notas-de-corte", changeFrequency: "monthly", priority: 0.8 },
  { path: "/simulados-enamed", changeFrequency: "weekly", priority: 0.9 },
  { path: "/simulados-enamed/o-que-e", changeFrequency: "yearly", priority: 0.7 },
  { path: "/simulados-enamed/como-interpretar-resultado", changeFrequency: "monthly", priority: 0.8 },
  { path: "/simulados-enamed/diagnostico-inicial", changeFrequency: "monthly", priority: 0.7 },
  { path: "/simulados-enamed/temporizado-vs-livre", changeFrequency: "yearly", priority: 0.7 },
  { path: "/simulados-enamed/questoes-comentadas", changeFrequency: "monthly", priority: 0.7 },
  { path: "/simulados-enamed/erros-comuns", changeFrequency: "monthly", priority: 0.7 },
  { path: "/areas", changeFrequency: "monthly", priority: 0.9 },
  { path: "/areas/clinica-medica", changeFrequency: "monthly", priority: 0.8 },
  { path: "/areas/clinica-medica/cardiologia", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/clinica-medica/pneumologia", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/clinica-medica/gastroenterologia", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/clinica-medica/nefrologia", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/clinica-medica/endocrinologia", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/clinica-medica/infectologia", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/cirurgia", changeFrequency: "monthly", priority: 0.8 },
  { path: "/areas/cirurgia/cirurgia-geral", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/cirurgia/trauma", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/pediatria", changeFrequency: "monthly", priority: 0.8 },
  { path: "/areas/pediatria/neonatologia", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/pediatria/urgencias-pediatricas", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/ginecologia-obstetricia", changeFrequency: "monthly", priority: 0.8 },
  { path: "/areas/ginecologia-obstetricia/pre-natal", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/ginecologia-obstetricia/mecanismo-parto", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/saude-coletiva", changeFrequency: "monthly", priority: 0.8 },
  { path: "/areas/saude-coletiva/sus", changeFrequency: "yearly", priority: 0.7 },
  { path: "/areas/etica-medica", changeFrequency: "monthly", priority: 0.8 },
  { path: "/areas/etica-medica/codigo-etica", changeFrequency: "yearly", priority: 0.7 },
  { path: "/preparacao", changeFrequency: "monthly", priority: 0.9 },
  { path: "/preparacao/cronograma-de-estudo", changeFrequency: "monthly", priority: 0.7 },
  { path: "/preparacao/tecnicas-de-estudo", changeFrequency: "yearly", priority: 0.7 },
  { path: "/preparacao/ultima-semana-de-prova", changeFrequency: "monthly", priority: 0.8 },
  { path: "/preparacao/dia-da-prova", changeFrequency: "monthly", priority: 0.8 },
  { path: "/carreira", changeFrequency: "monthly", priority: 0.9 },
  { path: "/carreira/residencia-medica", changeFrequency: "monthly", priority: 0.8 },
  { path: "/carreira/processo-seletivo-residencia", changeFrequency: "monthly", priority: 0.8 },
  { path: "/carreira/mercado-medico-brasil", changeFrequency: "yearly", priority: 0.6 },
  { path: "/ies", changeFrequency: "monthly", priority: 0.8 },
  { path: "/ies/avaliacao-mec-cpc", changeFrequency: "monthly", priority: 0.7 },
  { path: "/ies/sancoes-mec", changeFrequency: "monthly", priority: 0.7 },
  { path: "/ies/melhoria-de-nota", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog", changeFrequency: "daily", priority: 0.8 },
  { path: "/faq", changeFrequency: "monthly", priority: 0.7 },
  { path: "/glossario", changeFrequency: "monthly", priority: 0.7 },
  { path: "/comparativos", changeFrequency: "monthly", priority: 0.7 },
  { path: "/comparativos/enamed-vs-revalida", changeFrequency: "yearly", priority: 0.7 },
  { path: "/comparativos/enamed-vs-enade", changeFrequency: "yearly", priority: 0.7 },
  { path: "/comparativos/enamed-vs-residencia", changeFrequency: "yearly", priority: 0.7 },
  { path: "/comparativos/enamed-vs-r-plus", changeFrequency: "yearly", priority: 0.6 },
  { path: "/comparativos/tri-vs-classica", changeFrequency: "yearly", priority: 0.7 },
  { path: "/sobre", changeFrequency: "yearly", priority: 0.4 },
  { path: "/contato", changeFrequency: "yearly", priority: 0.4 },
  { path: "/politica-de-privacidade", changeFrequency: "yearly", priority: 0.2 },
  { path: "/termos-de-uso", changeFrequency: "yearly", priority: 0.2 },
  { path: "/politica-de-cookies", changeFrequency: "yearly", priority: 0.2 },
];
