export const siteConfig = {
  name: "Portal ENAMED",
  url: "https://provaenamed.com.br",
  description:
    "Portal de referência sobre o Exame Nacional de Avaliação da Formação Médica (ENAMED). Conteúdo factual, citável e atualizado para estudantes, médicos, IES e pesquisadores.",
  locale: "pt-BR",
};

export const sitemapRoutes: { path: string; changeFrequency: "daily" | "weekly" | "monthly" | "yearly"; priority: number }[] = [
  { path: "/", changeFrequency: "weekly", priority: 1.0 },
  { path: "/enamed", changeFrequency: "monthly", priority: 0.9 },
  { path: "/enamed/historia", changeFrequency: "yearly", priority: 0.7 },
  { path: "/enamed/elegibilidade", changeFrequency: "monthly", priority: 0.8 },
  { path: "/enamed/objetivos", changeFrequency: "monthly", priority: 0.7 },
  { path: "/enamed/diferencas", changeFrequency: "monthly", priority: 0.7 },
  { path: "/enamed/cronograma-aplicacao", changeFrequency: "monthly", priority: 0.8 },
  { path: "/prova-enamed", changeFrequency: "monthly", priority: 0.9 },
  { path: "/prova-enamed/teoria-resposta-item", changeFrequency: "yearly", priority: 0.8 },
  { path: "/prova-enamed/metodo-angoff", changeFrequency: "yearly", priority: 0.7 },
  { path: "/prova-enamed/numero-de-questoes", changeFrequency: "monthly", priority: 0.8 },
  { path: "/prova-enamed/tempo-de-prova", changeFrequency: "monthly", priority: 0.7 },
  { path: "/prova-enamed/notas-de-corte", changeFrequency: "monthly", priority: 0.8 },
  { path: "/simulados-enamed", changeFrequency: "weekly", priority: 0.9 },
  { path: "/areas", changeFrequency: "monthly", priority: 0.9 },
  { path: "/preparacao", changeFrequency: "monthly", priority: 0.9 },
  { path: "/carreira", changeFrequency: "monthly", priority: 0.9 },
  { path: "/ies", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog", changeFrequency: "daily", priority: 0.8 },
  { path: "/faq", changeFrequency: "monthly", priority: 0.7 },
  { path: "/glossario", changeFrequency: "monthly", priority: 0.7 },
  { path: "/sobre", changeFrequency: "yearly", priority: 0.4 },
  { path: "/contato", changeFrequency: "yearly", priority: 0.4 },
  { path: "/politica-de-privacidade", changeFrequency: "yearly", priority: 0.2 },
  { path: "/termos-de-uso", changeFrequency: "yearly", priority: 0.2 },
  { path: "/politica-de-cookies", changeFrequency: "yearly", priority: 0.2 },
];
